---
      - name: Create a new EC2 key
        ec2_key:
            name: "{{ key_name }}"
            region: "{{ region }}"
        register: ec2_key_result

      - name: Save private key
        copy: content="{{ ec2_key_result.key.private_key }}" dest="/etc/ansible/keys/{{ key_name }}.pem" mode=0400
        when: ec2_key_result.changed


      - name: send the private keys to the group_vars
        lineinfile:
             dest: /etc/ansible/group_vars/{{ item }}
             line: " ansible_ssh_private_key_file: /etc/ansible/keys/{{ key_name }}.pem"
             state: present
        with_items:
             - config
             - shard1
             - shard2
             - mongos

