---
      - name: Launch the new EC2 Instanc
        local_action: ec2 
                      group="{{ group_name }}-27018" 
                      instance_type="{{ shard1_type }}"
                      image="{{ image }}"
                      region="{{ region }}"
                      wait=yes
                      keypair="{{ key_name }}"
                      count="{{ shard1_count }}"
        register: ec2b




      - name: create a config section in host file
        lineinfile: 
          dest: /etc/ansible/hosts
          line: '[shard1]'
          state: present

      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region="{{ region }}" state=present
        with_items: "{{ ec2b.instances }}"
        args:
          tags:
            Name: shard1

      - name: Add the newly created EC2 instance(s) to host group
        lineinfile:
              dest: /etc/ansible/hosts
              line: '{{ item.private_ip }}'
              insertafter: '\[shard1\]'
        with_items: ec2b.instances

      - name: add IPs to the group_vars file
        lineinfile:
           dest: /etc/ansible/group_vars/shard1
           line: ' sha1_{{ item.ami_launch_index }}: {{ item.private_ip }}'
           state: present
        with_items: "{{ ec2b.instances }}"

      - name: add IPs to the group_vars file
        lineinfile:
           dest: /etc/ansible/group_vars/mongos
           line: ' sha1_{{ item.ami_launch_index }}: {{ item.private_ip }}'
           state: present
        with_items: "{{ ec2b.instances }}"


      - name: Wait for SSH to come up
        local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
        with_items: ec2b.instances
