---
# tasks file for ec2

 - name: create keys
   include: keys.yml
  
 - name: create the security group
   include: security.yml

 - name: create the VPC, subnets and the ec2 instances
   include: vpc.yml
 

